enum TBrandActionTypeEnum {
	GET_BRAND_SUCCESS = "GET_BRAND_SUCCESS",
	GET_BRAND_PENDING = "GET_BRAND_PENDING",
	GET_BRAND_FAILED = "GET_BRAND_FAILED",

	ADD_BRAND_PENDING = "ADD_BRAND_PENDING",
  	ADD_BRAND_FAILED = "ADD_BRAND_FAILED",
  	ADD_BRAND_SUCCESS = "ADD_BRAND_SUCCESS",

	DELETE_BRAND_PENDING = "DELETE_BRAND_PENDING",
  	DELETE_BRAND_FAILED = "DELETE_BRAND_FAILED",
  	DELETE_BRAND_SUCCESS = "DELETE_BRAND_SUCCESS",
}

export default TBrandActionTypeEnum;
