enum OrderActionTypeEnum {
  GET_ORDER_LIST_SUCCESS = "GET_ORDER_LIST_SUCCESS",
	GET_ORDER_LIST_PENDING = "GET_ORDER_LIST_PENDING",
	GET_ORDER_LIST_FAILED = "GET_ORDER_LIST_FAILED",
  GET_ORDER_BYID_SUCCESS = "GET_ORDER_BYID_SUCCESS",
	GET_ORDER_BYID_PENDING = "GET_ORDER_BYID_PENDING",
	GET_ORDER_BYID_FAILED = "GET_ORDER_BYID_FAILED",
}

export default OrderActionTypeEnum;
