enum UserActionTypeEnum {
  GET_USER_SUCCESS = "GET_USER_SUCCESS",
  GET_USER_FAILED = "GET_USER_FAILED",
  GET_USER_PENDING = "GET_USER_PENDING",

  DELETE_USER_PENDING = "DELETE_USER_PENDING",
  DELETE_USER_FAILED = "DELETE_USER_FAILED",
  DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS",
}

export default UserActionTypeEnum;
