enum TCategotyActionTypeEnum {
	GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS",
	GET_CATEGORY_PENDING = "GET_CATEGORY_PENDING",
	GET_CATEGORY_FAILED = "GET_CATEGORY_FAILED",
}

export default TCategotyActionTypeEnum;
