enum ProfileActionTypeEnum {
  PROFILE_LOADING = "PROFILE_LOADING",
  PROFILE_LOADED = "PROFILE_LOADED",
  GET_PROFILE = "GET_PROFILE",
  EDIT_PROFILE = "EDIT_PROFILE",

  SET_USER_ADDRESSES = "SET_USER_ADDRESSES",
  UPDATE_USER_ADDRESS = "UPDATE_USER_ADDRESS",
  DELETE_USER_ADDRESS = "DELETE_USER_ADDRESS",
  RESET_USER_ADDRESSES = "RESET_USER_ADDRESSES",
}

export default ProfileActionTypeEnum;
