enum ReportsActionTypeEnum {
  REPORTS_LOADING = "REPORTS_LOADING",
  REPORTS_LOADED = "REPORTS_LOADED",
  GET_CUSTOMER_REPORTS = "GET_CUSTOMER_REPORTS",
  GET_ORDERS_REPORTS = "GET_ORDERS_REPORTS",
  GET_PRODUCTS_REPORTS = "GET_PRODUCTS_REPORTS",
}

export default ReportsActionTypeEnum;
